# Generated by Django 5.2.4 on 2025-07-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_users_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
